[build-system]
requires = ["setuptools>=41.0",
	 "wheel>=0.33",
	 "setuptools_scm[toml]>=6.0",
	 "scipy",
	 "numpy"]

# [tool.pytest.ini_options]
# testpaths = [
#     "tests",
# ]

[tool.setuptools_scm]
write_to = "bigsmiles/_version.py"

[tool.black]
line-length = 100
