name: CI

on:
  push:
    branches:
      - main
      - trunk-merge/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ci-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install G-BigSMILES local package
        run: |
          python --version
          which python
          python -m pip install .

      - name: Run pytest on tests/
        run: python -m pytest ./tests/ -vvv
