name: CI

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ci-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
          $CONDA/bin/conda install pytest
          $CONDA/bin/conda install pip

      - name: Install
        run: $CONDA/bin/pip install .

      - name: Run tests
        run: |
          $CONDA/bin/pytest
