name: CI Coverage

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ci-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install G-BigSMILES local package
        run: |
          python -m pip install pytest-cov
          python -m pip install .

      - name: Run Pytest
        shell: bash -l {0}
        run: |
          pytest --cov=src/gbigsmiles --cov-fail-under=85
