name: CI Coverage

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ci-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pip install G-BigSMILES local package
        run: python -m pip install .

      - name: Run Pytest
        shell: bash -l {0}
        run: |
          pytest --cov --cov-fail-under=85
