name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
