name: trunk

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main
jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
