on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  trunk:
    runs-on: ubuntu-20.04
    name: trunk code style
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # Caching is only needed when using ephemeral CI runners
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}
        # Python setup
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.4.0-beta
