name: CI

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main
jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
  ci-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
          $CONDA/bin/conda install pytest
          $CONDA/bin/conda install pip

      - name: Install
        run: $CONDA/bin/pip install .

      - name: Run tests
        run: |
          $CONDA/bin/pytest
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install python dependencies
        run: |
          sudo apt install jupyter-nbconvert
          $CONDA/bin/conda env update --file environment.yml --name base
          $CONDA/bin/conda install pytest
          $CONDA/bin/conda install pip
          $CONDA/bin/conda install ipython
          $CONDA/bin/conda install -c conda-forge pydot
      - name: Install
        run: $CONDA/bin/pip install .
      - name: Generate script from jupyter
        run: jupyter nbconvert --to python bigsmiles_gen.ipynb
      - name: Run the script
        run: $CONDA/bin/python bigsmiles_gen.py
      - name: Generate SI script from jupyter
        run: jupyter nbconvert --to python SI.ipynb
      - name: Run the script
        run: $CONDA/bin/python SI.py
