name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
  ci-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install
        run: pip install .

      - name: Run tests
        run: |
          pytest
